parameters:
    database_driver:   pdo_mysql
    database_socket:     /tmp/mysql.sock
    database_port:     ~
    database_name:     trycatch
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
